### ISSUE TITLE
Screenshot is the wrong size

### ISSUE THREAD

**Issue by onedrawingperday** [dgraph-io/hugo-dgraph-theme#8]
Hello @paulftw 

I noticed that you updated the theme's images recently. 

However now the [screenshot](https://github.com/dgraph-io/hugo-dgraph-theme/blob/master/images/screenshot.png) has the wrong dimensions, it should be 1500×1000 in pixels. Also it should feature only the theme's layout (not the browser chrome)  and it shouldn't have transparency. 

For future reference please use the Hugo Themes [README](https://github.com/gohugoio/hugoThemes#media)

Can you please fix the screenshot's dimensions? 

Thanks

**Comment by paulftw** [comment]
Yes, will fix the dimensions. Thanks for pointing that out.

**Comment by paulftw** [comment]
this commit should've fixed this: https://github.com/dgraph-io/hugo-dgraph-theme/commit/ced998bb5fd1e01e78eed39d03c60072d1fadde5

feel free to reopen if I missed anything
